# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
<<<<<<< HEAD
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
=======
# which you are expected to set up once and rarely need to edit after that.
>>>>>>> 39f567daed115bfde66d4e0555538bdf04c56e10
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
<<<<<<< HEAD
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
=======
>>>>>>> 39f567daed115bfde66d4e0555538bdf04c56e10
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
<<<<<<< HEAD
url: "http://example.com" # the base hostname & protocol for your site
=======
url: "http://yourdomain.com" # the base hostname & protocol for your site
>>>>>>> 39f567daed115bfde66d4e0555538bdf04c56e10
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
<<<<<<< HEAD
theme: minima
=======
>>>>>>> 39f567daed115bfde66d4e0555538bdf04c56e10
